--------------------------------------------------------
-- Archivo creado  - martes-febrero-11-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table COMERCIANTE
--------------------------------------------------------

  CREATE TABLE "COMERCIANTE" 
   (	"ID_COMERCIANTE" NUMBER(19,0), 
	"NOMBRE" VARCHAR2(255 CHAR), 
	"MUNICIPIO" VARCHAR2(255 CHAR), 
	"TELEFONO" VARCHAR2(255 CHAR), 
	"CORREO_ELECTRONICO" VARCHAR2(255 CHAR), 
	"FECHA_REGISTRO" DATE NOT NULL ENABLE, 
	"ESTADO" VARCHAR2(255 CHAR), 
	 CHECK (estado in ('ACTIVO', 'INACTIVO')) ENABLE, 
	 PRIMARY KEY ("ID_COMERCIANTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Table ESTABLECIMIENTO
--------------------------------------------------------

  CREATE TABLE "ESTABLECIMIENTO" 
   (	"ID_ESTABLECIMIENTO" NUMBER(19,0), 
	"ID_COMERCIANTE" NUMBER(19,0), 
	"INGRESOS" NUMBER(38,2), 
	"NOMBRE_ESTABLECIMIENTO" VARCHAR2(255 CHAR), 
	"NUMERO_EMPLEADOS" NUMBER(10,0), 
	 PRIMARY KEY ("ID_ESTABLECIMIENTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_COMERCIANTE" FOREIGN KEY ("ID_COMERCIANTE")
	  REFERENCES "COMERCIANTE" ("ID_COMERCIANTE") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Table USUARIO
--------------------------------------------------------

  CREATE TABLE "USUARIO" 
   (	"ID_USUARIO" NUMBER(19,0), 
	"CONTRASENA" VARCHAR2(255 CHAR), 
	"CORREO_ELECTRONICO" VARCHAR2(255 CHAR), 
	"NOMBRE" VARCHAR2(255 CHAR), 
	"ROL" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
REM INSERTING into COMERCIANTE
SET DEFINE OFF;
Insert into COMERCIANTE (ID_COMERCIANTE,NOMBRE,MUNICIPIO,TELEFONO,CORREO_ELECTRONICO,FECHA_REGISTRO,ESTADO) values ('1','Felipe Caicedo','Cali','32635987654','Felipe.Caicedo@gmail.com',to_date('05/02/25','DD/MM/RR'),'ACTIVO');
Insert into COMERCIANTE (ID_COMERCIANTE,NOMBRE,MUNICIPIO,TELEFONO,CORREO_ELECTRONICO,FECHA_REGISTRO,ESTADO) values ('24','Camila Vargas','Santa Marta','3214789654','camila.vargas@email.com',to_date('10/02/25','DD/MM/RR'),'ACTIVO');
Insert into COMERCIANTE (ID_COMERCIANTE,NOMBRE,MUNICIPIO,TELEFONO,CORREO_ELECTRONICO,FECHA_REGISTRO,ESTADO) values ('22','Sofía Ríos','Ibagué','3179638524','sofia.rios@email.com',to_date('12/02/25','DD/MM/RR'),'ACTIVO');
Insert into COMERCIANTE (ID_COMERCIANTE,NOMBRE,MUNICIPIO,TELEFONO,CORREO_ELECTRONICO,FECHA_REGISTRO,ESTADO) values ('23','Daniel Ortega','Villavicencio','3165897412','daniel.ortega@email.com',to_date('11/02/25','DD/MM/RR'),'INACTIVO');
Insert into COMERCIANTE (ID_COMERCIANTE,NOMBRE,MUNICIPIO,TELEFONO,CORREO_ELECTRONICO,FECHA_REGISTRO,ESTADO) values ('25','Andrés Castro','Cúcuta','3198745632','andres.castro@email.com',to_date('09/02/25','DD/MM/RR'),'ACTIVO');
Insert into COMERCIANTE (ID_COMERCIANTE,NOMBRE,MUNICIPIO,TELEFONO,CORREO_ELECTRONICO,FECHA_REGISTRO,ESTADO) values ('26','Laura Díaz','Bucaramanga','3224567893','laura.diaz@email.com',to_date('08/02/25','DD/MM/RR'),'INACTIVO');
Insert into COMERCIANTE (ID_COMERCIANTE,NOMBRE,MUNICIPIO,TELEFONO,CORREO_ELECTRONICO,FECHA_REGISTRO,ESTADO) values ('27','Santiago Herrera','Manizales','3142589637','santiago.herrera@email.com',to_date('07/02/25','DD/MM/RR'),'ACTIVO');
Insert into COMERCIANTE (ID_COMERCIANTE,NOMBRE,MUNICIPIO,TELEFONO,CORREO_ELECTRONICO,FECHA_REGISTRO,ESTADO) values ('28','María González','Pereira','3187412589','maria.gonzalez@email.com',to_date('06/02/25','DD/MM/RR'),'ACTIVO');
Insert into COMERCIANTE (ID_COMERCIANTE,NOMBRE,MUNICIPIO,TELEFONO,CORREO_ELECTRONICO,FECHA_REGISTRO,ESTADO) values ('29','Jorge López','Barranquilla','3123698527','jorge.lopez@email.com',to_date('05/02/25','DD/MM/RR'),'INACTIVO');
Insert into COMERCIANTE (ID_COMERCIANTE,NOMBRE,MUNICIPIO,TELEFONO,CORREO_ELECTRONICO,FECHA_REGISTRO,ESTADO) values ('30','Ana Ramírez','Cartagena','3204567890','ana.ramirez@email.com',to_date('04/02/25','DD/MM/RR'),'ACTIVO');
Insert into COMERCIANTE (ID_COMERCIANTE,NOMBRE,MUNICIPIO,TELEFONO,CORREO_ELECTRONICO,FECHA_REGISTRO,ESTADO) values ('31','Pedro Sánchez','Cali','3119876543','pedro.sanchez@email.com',to_date('03/02/25','DD/MM/RR'),'ACTIVO');
Insert into COMERCIANTE (ID_COMERCIANTE,NOMBRE,MUNICIPIO,TELEFONO,CORREO_ELECTRONICO,FECHA_REGISTRO,ESTADO) values ('32','Luisa Fernández','Medellín','3002564789','luisa.fernandez@email.com',to_date('02/02/25','DD/MM/RR'),'INACTIVO');
REM INSERTING into ESTABLECIMIENTO
SET DEFINE OFF;
Insert into ESTABLECIMIENTO (ID_ESTABLECIMIENTO,ID_COMERCIANTE,INGRESOS,NOMBRE_ESTABLECIMIENTO,NUMERO_EMPLEADOS) values ('3','1','120000,5','Restaurante El Buen Sabor','25');
REM INSERTING into USUARIO
SET DEFINE OFF;
Insert into USUARIO (ID_USUARIO,CONTRASENA,CORREO_ELECTRONICO,NOMBRE,ROL) values ('9','12345','andres.calero@gmail.com','Andres Calero','AUXILIAR_REGISTRO');
Insert into USUARIO (ID_USUARIO,CONTRASENA,CORREO_ELECTRONICO,NOMBRE,ROL) values ('8','12345','juan.perez@gmail.com','Juan Pérez','ADMINISTRADOR');
--------------------------------------------------------
--  DDL for Index SYS_C007145
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C007145" ON "COMERCIANTE" ("ID_COMERCIANTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Index SYS_C007149
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C007149" ON "ESTABLECIMIENTO" ("ID_ESTABLECIMIENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Index SYS_C007145
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C007145" ON "COMERCIANTE" ("ID_COMERCIANTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Index SYS_C007149
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C007149" ON "ESTABLECIMIENTO" ("ID_ESTABLECIMIENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"
--------------------------------------------------------
--  DDL for Trigger TRG_COMERCIANTE_ID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TRG_COMERCIANTE_ID" 
BEFORE INSERT ON InfoMercado.comerciante
FOR EACH ROW
BEGIN
    :new.id_comerciante := seq_comerciante.NEXTVAL;
END;
ALTER TRIGGER "TRG_COMERCIANTE_ID" ENABLE
--------------------------------------------------------
--  DDL for Trigger TRG_ESTABLECIMIENTO_ID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TRG_ESTABLECIMIENTO_ID" 
BEFORE INSERT ON InfoMercado.establecimiento
FOR EACH ROW
BEGIN
    :new.id_establecimiento := seq_establecimiento.NEXTVAL;
END;
ALTER TRIGGER "TRG_ESTABLECIMIENTO_ID" ENABLE
--------------------------------------------------------
--  DDL for Trigger TRG_USUARIO_ID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TRG_USUARIO_ID" 
BEFORE INSERT ON InfoMercado.usuario
FOR EACH ROW
BEGIN
    :new.id_usuario := seq_usuario.NEXTVAL;
END;

ALTER TRIGGER "TRG_USUARIO_ID" ENABLE
--------------------------------------------------------
--  DDL for Trigger TRG_COMERCIANTE_ID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TRG_COMERCIANTE_ID" 
BEFORE INSERT ON InfoMercado.comerciante
FOR EACH ROW
BEGIN
    :new.id_comerciante := seq_comerciante.NEXTVAL;
END;
ALTER TRIGGER "TRG_COMERCIANTE_ID" ENABLE
--------------------------------------------------------
--  DDL for Trigger TRG_ESTABLECIMIENTO_ID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TRG_ESTABLECIMIENTO_ID" 
BEFORE INSERT ON InfoMercado.establecimiento
FOR EACH ROW
BEGIN
    :new.id_establecimiento := seq_establecimiento.NEXTVAL;
END;
ALTER TRIGGER "TRG_ESTABLECIMIENTO_ID" ENABLE
--------------------------------------------------------
--  DDL for Trigger TRG_USUARIO_ID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "TRG_USUARIO_ID" 
BEFORE INSERT ON InfoMercado.usuario
FOR EACH ROW
BEGIN
    :new.id_usuario := seq_usuario.NEXTVAL;
END;

ALTER TRIGGER "TRG_USUARIO_ID" ENABLE
--------------------------------------------------------
--  Constraints for Table COMERCIANTE
--------------------------------------------------------

  ALTER TABLE "COMERCIANTE" ADD PRIMARY KEY ("ID_COMERCIANTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
  ALTER TABLE "COMERCIANTE" ADD CHECK (estado in ('ACTIVO', 'INACTIVO')) ENABLE
  ALTER TABLE "COMERCIANTE" MODIFY ("FECHA_REGISTRO" NOT NULL ENABLE)
--------------------------------------------------------
--  Constraints for Table ESTABLECIMIENTO
--------------------------------------------------------

  ALTER TABLE "ESTABLECIMIENTO" ADD PRIMARY KEY ("ID_ESTABLECIMIENTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
--------------------------------------------------------
--  Ref Constraints for Table ESTABLECIMIENTO
--------------------------------------------------------

  ALTER TABLE "ESTABLECIMIENTO" ADD CONSTRAINT "FK_COMERCIANTE" FOREIGN KEY ("ID_COMERCIANTE")
	  REFERENCES "COMERCIANTE" ("ID_COMERCIANTE") ENABLE
